version: '3.4'

services:
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'app'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'aspilos'
       MYSQL_ROOT_PASSWORD: 'aspilos'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/aspilos
    ports:
      - "8000:8000"
    depends_on:
      - db